// Possible posts and responses.
// Note: all of these potentialPosts will be prepended when loaded with "I feel ".
export const potentialPosts = [
    "happy",
    "very happy",
    "👍",
    "☺️",
    "😄",
    "😂",
    "💜",
    "sad",
    "very sad",
    "🙁",
    "☹️",
    "👎",
    "😦",
    "😢",
    "😭",
    "💔",
    "angry",
    "very angry",
    "😟",
    "😠",
    "disgusted",
    "very disgusted",
    "🤢",
    "🤮",
    "surprised",
    "very surprised",
    "😯",
    "😮",
    "scared",
    "very scared",
    "😨",
    "😱",
    "😧",
    "empty",
    "very empty",
    "😐",
    "⚰️",
    "confused",
    "🤔",
    "😕",
    "lost",
    "😶"
];

export const potentialResponses = [
    "I care about your feelings",
    "I care about you",
    "I hope this response provides you with empty validation!",
    "This is emotional support",
    "This is empathy",
    "😢",
    "😌",
    "☺️",
    "Good for you!",
    "Nice!",
    "Great!",
    "👍",
    "✋",
    "💯",
    "👐",
    "I am there for you.",
    "I believe in you.",
    "🤗",
    "Sounds good",
    "K",
    "Ouch",
    "Oof",
    "Yikes!"
];

// Potential bot responses, same as potentialResponses but subdivided into buckets categorizing their suitability as responses to statements of varying emotional valence.
export const botResponses = {
    'Negative': [
        "This is empathy",
        "😢",
        "I am there for you.",
        "Oof",
        "Yikes!",
        "Ouch",
        "🤗",
        "I believe in you.",
        "I care about you",
        "This is emotional support",
    ],
    'Neutral': [
         "K",
         "Sounds good",
         "I hope this response provides you with empty validation!",
         "I care about your feelings",
        ],
    'Positive': [
        "☺️",
        "✋",
        "💯",
        "👐",
        "😌",
        "👍",
        "Good for you!",
        "Nice!",
        "Great!",
    ]
};
